export default function Head() {
  return (
    <>
      <title>Experiments with NextJS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Experimental NextJS site Generated by create-next-app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
